### PR TITLE
t/227: Contextual toolbar should re–position correctly on window scroll

### LINKED ISSUE #227: Contextual toolbar is incorrectly positioned on scroll
may-10-2017 15-14-54

And it blinks ugly.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Contextual toolbar should re–position correctly on window scroll. Closes #227.

---

### Additional information

Requires https://github.com/ckeditor/ckeditor5-utils/issues/157.
Also closes https://github.com/ckeditor/ckeditor5-ui/issues/195.

### CODE REVIEW

File: tests/toolbar/contextual/contextualtoolbar.js [hunk 1]
```diff
@@ -160,7 +160,7 @@ describe( 'ContextualToolbar', () => {
 					view: contextualToolbar.toolbarView,
 					balloonClassName: 'ck-toolbar-container ck-editor-toolbar-container',
 					position: {
-						target: forwardSelectionRect,
```
Comment (oleq) [inline tests/toolbar/contextual/contextualtoolbar.js]: Note that tests previously passed probably because the `forwardSelectionRect` and `backwardSelectionRect` look exactly the same. Please double–check it though.

**Comment by oskarwrobel** [comment]
`target` function for `CT` is not called on scroll.

may-16-2017 14-17-49

**Comment by oleq** [comment]
I pushed a commit that should fix it @oskarwrobel. Please let me know if it works for you.
