### PR TITLE
t/145: Fixed ViewCollection and DOM desynchronise in some cases.

### LINKED ISSUE #145: ViewCollection and DOM desynchronise in some cases
Steps to reproduce:

1. `VC` is used in a DOM template.
2. Template renders.
3. Contents of `VC` change, i.e. views are removed.
4. `VC.init()` is called.

**Expected**: Children of `VC#_parentElement` reflect directly `View#element` of the views in the colleciton, in the count and order.

**Actual**: There are some extra elements in `#_parentElement`, which belong to views, which i.e. have been removed in (3.) but the removal had not been reflected in DOM.

This happens because of `this.ready` conditions in https://github.com/ckeditor/ckeditor5-ui/blob/master/src/viewcollection.js#L37, which freeze the `VC` in DOM until `init()` is called. 

Because of that, if the VC has been rendered in some template before `init()`, a view can be added to the collection, but it's `#element` will not land there in DOM. Similarly, a view can be removed, but its `#element` still remains in DOM. A serious source of bugs, hard to debug.

### PR DESCRIPTION
**Pull request by oleq**
Fixes #145.

### CODE REVIEW

File: src/dropdown/dropdownview.js [hunk 1]
```diff
@@ -22,6 +22,17 @@ export default class DropdownView extends View {
 	constructor( locale, buttonView, panelView ) {
 		super( locale );
 
+		// Extend button's template before it's registered as a child of the dropdown because
+		// by doing so, its #element is rendered and any post–render template extension will
+		// not be reflected in DOM.
+		Template.extend( buttonView.template, {
```
Comment (oleq) [inline src/dropdown/dropdownview.js]: The only drawback of the new approach, aside from some minor performance impact, is that adding a `View` to any collection means immediate rendering view's `#element`, to synchronize the VC in DOM. 

It's important to remember that fact because i.e. extending view's template after that will have no reflection in DOM since the template has already been rendered.

Comment (oskarwrobel) [inline src/dropdown/dropdownview.js]: There is a chance that someone will modify template in wrong moment and result will be different than expected and there will be no error or warning. I know that `Template` does not know anything about the `View`, bu this is the second place (first: https://github.com/ckeditor/ckeditor5-ui/issues/139) where `Template` can be used incorrectly without any warning.

Comment (oleq) [inline src/dropdown/dropdownview.js]: There's an easy fix for this, I think. 

We render a `Template` instance only once despite the fact that it's possible to re–render it and use it as a factory. Because of that, we can simply introduce a flag `Template#rendered`, which would be set after `render()` is executed. Then, [`Template.extend()`](https://github.com/ckeditor/ckeditor5-ui/blob/t/145/src/template.js#L234-L236) would check for that flag, and display a warning informing about attempting to extend an instance, which has already been rendered.

WDYT?

Comment (oleq) [inline src/dropdown/dropdownview.js]: Created an issue https://github.com/ckeditor/ckeditor5-ui/issues/148.
