### PR TITLE
t/92: Fixed: A View#id Number breaks parent ViewCollection.

### LINKED ISSUE #93: Problem with id property in view class
`id` property could be a [common property](https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/inputtext/inputtextview.js#L34) for input components, but using this property can blow up the editor. It happens when `View` instance is beeing [added to the views collection](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/controller.js#L220). This is because `id` property is [reserved](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/collection.js#L55) for collection item and has to be a `String`.

### PR DESCRIPTION
**Pull request by oleq**
Fixes #93.

### CODE REVIEW

File: src/viewcollection.js [hunk 1]
```diff
@@ -70,6 +70,10 @@ export default class ViewCollection extends Collection {
 		 * @member {HTMLElement} ui.ViewCollection#_boundItemsToViewsMap
 		 */
 		this._boundItemsToViewsMap = new Map();
+
+		// An #id Number attribute should be legal and not break the `ViewCollection` instance.
+		// https://github.com/ckeditor/ckeditor5-ui/issues/93
+		this._idProperty = 'viewUid';
```
Comment (Reinmar) [inline src/viewcollection.js]: It's private property. Specify it via the constructor (`options.idProperty`).
