### PR TITLE
Used editableElement after uiReady

### LINKED ISSUE #424: Balloon Toolbar sample does not work
screen shot 2018-07-04 at 17 43 51

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Used editableElement after uiReady. Closes #424.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

File: src/toolbar/balloon/balloontoolbar.js [hunk 1]
```diff
@@ -59,8 +59,8 @@ export default class BalloonToolbar extends Plugin {
 		 * @type {module:utils:focustracker~FocusTracker}
 		 */
 		this.focusTracker = new FocusTracker();
-		this.focusTracker.add( editor.ui.view.editableElement );
 		this.focusTracker.add( this.toolbarView.element );
+		editor.once( 'uiReady', () => this.focusTracker.add( editor.ui.view.editableElement ) );
```
Comment (oleq) [inline src/toolbar/balloon/balloontoolbar.js]: Why not simply moving both `add()` to `init()` below?

Comment (oskarwrobel) [reply src/toolbar/balloon/balloontoolbar.js]: I won't help. Plugin#init is before UI#init.

Comment (oleq) [reply src/toolbar/balloon/balloontoolbar.js]: Alright, that's a good point 😜Then put both `FT.add()` calls in there because now it looks like this one is super-special for some reason.

File: tests/toolbar/balloon/balloontoolbar.js [hunk 2]
```diff
@@ -138,6 +139,17 @@ describe( 'BalloonToolbar', () => {
 		}, 100 );
 	} );
 
+	// See https://github.com/ckeditor/ckeditor5-ui/issues/424.
+	// This test should be removed after fixing this https://github.com/ckeditor/ckeditor5-core/issues/137.
```
Comment (oleq) [inline tests/toolbar/balloon/balloontoolbar.js]: When we remove this test, the change with `editor.once( 'uiReady', () => {` will be left without any unit test. Is that right?
